name: teste3
description: "A new Flutter project. Created by Slidy"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.8.1
  font_awesome: ^5.10.1
  google_sign_in: ^4.4.4
  firebase_auth: ^0.16.0
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  flutter_modular: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.2.1
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

scripts:
  clean: flutter clean & flutter pub get
  mobx: slidy run clean  & flutter pub run build_runner build --delete-conflicting-outputs